kind: pipeline
name: default

steps:
  - name: prepare
    image: twite/db-backup-tool-base:0.0.1
    user: root
    commands:
      - chown -R gradle:gradle /drone/src/
  - name: test
    user: gradle
    image: twite/db-backup-tool-base:0.0.1
    commands:
      - gradle test --stacktrace
    environment:
      TESTS_DROPBOX_ACCESS_TOKEN:
        from_secret: testsDropboxAccessToken