version: '3'
services:
  db-backup-tool:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - USERCONFIG_WEBUILOGIN=
      - USERCONFIG_WEBUIPASSWORD=
    ports:
      - 8080:8080
    network_mode: host