FROM gradle:5.4.1-jre11
USER root
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && apt-get update && apt-get install -y --no-install-recommends postgresql-client-10
RUN chown -R gradle:gradle /usr/bin/gradle \
    && chown -R gradle:gradle /opt/gradle/bin