package com.blog.entities.database;

import org.jetbrains.annotations.NotNull;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Optional;

/**
 * This entity represents database settings.
 * <p>
 * To create a new instance of this entity use one of the static builder factory for each database type.
 * (e.g. {@link #postgresSettings(PostgresSettings)}.
 * <p>
 * Example of creating a new instance:
 * <code>
 * PostgresSettings postgresSettings = new PostgresSettings();
 * // set required fields
 * DatabaseSettings databaseSettings = DatabaseSettings.postgresSettings(postgresSettings)
 * .withSettingsName(settingsName)
 * .withHost(host)
 * .withPort(port)
 * .withDatabaseName(name)
 * .withLogin(login)
 * .withPassword(password)
 * .build();
 * </code>
 * <p>
 * This entity is mainly used by {@link com.blog.service.databaseBackup.DatabaseBackup} services to access database.
 */
@Entity
@Table(name = "database_settings")
public class DatabaseSettings {
    /**
     * Identifier of each database settings.
     * <p>
     * This field is set by user and not generated by database. Must be unique.
     */
    @Id
    private String settingsName;

    /**
     * Database type.
     * <p>
     * This field is set automatically by builder when using one of the static builder factory methods.
     *
     * @see DatabaseType
     */
    @Enumerated(EnumType.STRING)
    @Column(updatable = false)
    private DatabaseType type;

    /**
     * Database host.
     */
    private String host;

    /**
     * Database port.
     */
    private int port;

    /**
     * Database name.
     */
    private String name;

    /**
     * Database login.
     * <p>
     * This field is not printed by {@link #toString()} method.
     */
    private String login;

    /**
     * Database password.
     * <p>
     * This field is not printed by {@link #toString()} method.
     */
    private String password;

    /**
     * Settings creation time.
     */
    @Column(updatable = false)
    private LocalDateTime date;

    /**
     * This field contains database specific fields depending on database type.
     * <p>
     * Storing database specific fields as single column allows to not overburden database settings table and the entity as well.
     * <p>
     * This field is not exposed to entity's API and instead provided getters for each database type should be used
     * (e.g. {@link #getPostgresSettings()}.
     * <p>
     * This field is converted into JSON string and back to POJO by {@link AdditionalDatabaseSettingsConverter} class.
     */
    @Column(name = "additionalFields")
    @Convert(converter = AdditionalDatabaseSettingsConverter.class)
    private AdditionalDatabaseSettings additionalDatabaseSettings;

    DatabaseSettings() {
    }

    private DatabaseSettings(@NotNull DatabaseType type, @NotNull String settingsName, @NotNull LocalDateTime date,
                             @NotNull String host, int port,
                             @NotNull String name, @NotNull String login, @NotNull String password,
                             @NotNull AdditionalDatabaseSettings additionalDatabaseSettings) {
        this.type = Objects.requireNonNull(type);
        this.settingsName = Objects.requireNonNull(settingsName);
        this.date = Objects.requireNonNull(date);
        this.host = Objects.requireNonNull(host);
        this.port = port;
        this.name = Objects.requireNonNull(name);
        this.login = Objects.requireNonNull(login);
        this.password = Objects.requireNonNull(password);
        this.additionalDatabaseSettings = Objects.requireNonNull(additionalDatabaseSettings);
    }

    /**
     * Static builder factory method for PostgreSQL settings.
     *
     * @param postgresSettings Postgres settings
     * @return Builder with PostgresSettings and according type set.
     */
    public static Builder postgresSettings(@NotNull PostgresSettings postgresSettings) {
        Builder builder = new Builder();
        builder.type = DatabaseType.POSTGRES;
        builder.postgresSettings = Objects.requireNonNull(postgresSettings);
        return builder;
    }

    public DatabaseType getType() {
        return type;
    }

    public String getSettingsName() {
        return settingsName;
    }

    public void setSettingsName(String settingsName) {
        this.settingsName = settingsName;
    }

    public String getHost() {
        return host;
    }

    void setHost(String host) {
        this.host = host;
    }

    public int getPort() {
        return port;
    }

    void setPort(int port) {
        this.port = port;
    }

    public String getName() {
        return name;
    }

    void setName(String name) {
        this.name = name;
    }

    public String getLogin() {
        return login;
    }

    void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    void setPassword(String password) {
        this.password = password;
    }

    public LocalDateTime getDate() {
        return date;
    }

    void setDate(LocalDateTime date) {
        this.date = date;
    }

    void setAdditionalDatabaseSettings(AdditionalDatabaseSettings additionalDatabaseSettings) {
        this.additionalDatabaseSettings = additionalDatabaseSettings;
    }

    public Optional<PostgresSettings> getPostgresSettings() {
        return Optional.ofNullable(additionalDatabaseSettings.getPostgresSettings());
    }

    @Override
    public String toString() {
        return "DatabaseSettings{" +
                ", settingsName=" + settingsName +
                ", type=" + type +
                ", host='" + host + '\'' +
                ", port='" + port + '\'' +
                ", databaseName='" + name + '\'' +
                ", login=***'" + '\'' +
                ", password=***'" + '\'' +
                ", date=" + date +
                ", additionalDatabaseSettings=" + additionalDatabaseSettings +
                '}';
    }

    /**
     * Builder for this entity.
     * <p>
     * All fields are required and there are no optional fields.
     */
    public static final class Builder {
        private DatabaseType type;
        private String settingsName;
        private LocalDateTime date;
        private String host;
        private int port;
        private String databaseName;
        private String login;
        private String password;
        private PostgresSettings postgresSettings;

        private Builder() {
        }

        public Builder withHost(@NotNull String host) {
            this.host = Objects.requireNonNull(host);
            return this;
        }

        public Builder withPort(int port) {
            this.port = port;
            return this;
        }

        public Builder withDatabaseName(@NotNull String name) {
            this.databaseName = Objects.requireNonNull(name);
            return this;
        }

        public Builder withLogin(@NotNull String login) {
            this.login = Objects.requireNonNull(login);
            return this;
        }

        public Builder withPassword(@NotNull String password) {
            this.password = Objects.requireNonNull(password);
            return this;
        }

        public Builder withSettingsName(@NotNull String settingsName) {
            this.settingsName = settingsName;
            return this;
        }

        public Builder withDate(@NotNull LocalDateTime date) {
            this.date = date;
            return this;
        }

        public DatabaseSettings build() {
            AdditionalDatabaseSettings additionalDatabaseSettings = new AdditionalDatabaseSettings(type, postgresSettings);
            return new DatabaseSettings(type, settingsName, date, host, port, databaseName, login, password, additionalDatabaseSettings);
        }
    }
}
